# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: /project
    weight: 11
  - name: Publications
    url: publication/
    weight: 12
  - name: test
    url: test/
    weight: 15
  # - name: Experience
  #   url: /#experience  # means element in the page
  #   weight: 13
  - name: Experience
    url: experience/
    weight: 20
  # - name: CV
  #   url: uploads/ANDERSON_Matt.pdf
  #   weight: 70